spring:
  application:
    name: reenttry-by-face
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
loggin:
logging:
  level:
    root: info
    io.github.nicechester: debug
